import { describe, it, expect, vi, beforeEach } from 'vitest';
import { NexusRouter } from '../../../src/core/NexusRouter';
import { invokeNexusLLM } from '../../../src/lib/providers/nexusllm';
import { Plugin, PluginManager } from '../../../src/core/PluginManager';
import { RouterContext, ReviewerOutput } from '../../../src/types/router';

// Mock dependencies
vi.mock('../../../src/core/PluginManager');
vi.mock('../../../src/lib/providers/nexusllm', () => ({
  invokeNexusLLM: vi.fn(),
}));

describe('NexusRouter: Orchestration', () => {
  let router: NexusRouter;
  let mockPluginManager: PluginManager;

  beforeEach(() => {
    vi.resetAllMocks();
    mockPluginManager = new PluginManager();
    router = new NexusRouter(mockPluginManager);
  });

  it('should format the final output using the FormatterPlugin', async () => {
    vi.mocked(invokeNexusLLM).mockResolvedValue({
      model: 'Qwen2.5',
      response: 'some llm response',
    });
    const result = await router.route('some input', { useCase: 'General text generation' });

    expect(result.output).toBeTypeOf('object');
    expect(result.output).toHaveProperty('suggestion', 'some llm response');
    expect(result.pluginsUsed).not.toContain('formatter');
  });

  describe('Premium Access Logic', () => {
    it('should NOT execute plugins if the contributor does not have premium access', async () => {
      vi.mocked(invokeNexusLLM).mockResolvedValue({
        model: 'StarCoder2',
        response: 'some llm response',
      });
      const mockPlugin: Plugin = {
        name: 'regex',
        run: vi.fn(),
      };
      vi.spyOn(mockPluginManager, 'get').mockReturnValue(mockPlugin);

      const context: RouterContext = {
        useCase: 'Code generation',
        plugins: ['regex'],
        contributor: { id: 'non-premium-user', secretBadge: false },
      };

      const result = await router.route('hello world', context);

      expect(mockPlugin.run).not.toHaveBeenCalled();
      expect(result.pluginsUsed).toEqual([]);
      expect(invokeNexusLLM).toHaveBeenCalledWith('Code generation', 'hello world', {
        model: 'StarCoder2',
      });
    });

    it('should execute plugins if the contributor has the secretBadge', async () => {
      vi.mocked(invokeNexusLLM).mockResolvedValue({
        model: 'StarCoder2',
        response: 'some llm response',
      });
      const mockPlugin: Plugin = {
        name: 'regex',
        run: vi.fn().mockResolvedValue({ modifiedInput: 'some input' }),
      };
      vi.spyOn(mockPluginManager, 'get').mockReturnValue(mockPlugin);

      const context: RouterContext = {
        useCase: 'Code generation',
        plugins: ['regex'],
        contributor: { id: 'premium-user', secretBadge: true },
      };

      await router.route('hello world', context);

      expect(mockPlugin.run).toHaveBeenCalled();
    });
  });

  describe('Fallback Orchestration', () => {
    it('should attempt a fallback to a second model if the first fails for a premium user', async () => {
      const mockInvoke = vi.mocked(invokeNexusLLM);
      mockInvoke
        .mockRejectedValueOnce(new Error('Initial model failed'))
        .mockResolvedValueOnce({ model: 'Qwen2.5', response: 'fallback response' });

      const context: RouterContext = {
        useCase: 'Code generation',
        contributor: { id: 'premium-fallback-user', secretBadge: true },
      };

      const result = await router.route('some code', context);

      expect(mockInvoke).toHaveBeenCalledTimes(2);
      expect(mockInvoke).toHaveBeenCalledWith('Code generation', 'some code', {
        model: 'StarCoder2',
      });
      expect(mockInvoke).toHaveBeenCalledWith('Code generation', 'some code', { model: 'Qwen2.5' });
      expect(result.model).toBe('Qwen2.5');
      expect(result.output).toHaveProperty('suggestion', 'fallback response');
      expect(result.fallbackModel).toBe('StarCoder2');
      expect(result.output).toHaveProperty(
        'reviewerNote',
        `Primary model failed. This response was generated by the fallback model: ${result.fallbackModel}.`
      );
      expect(result.error).toBeUndefined();
    });

    it('should NOT attempt a fallback for a non-premium user', async () => {
      const mockInvoke = vi.mocked(invokeNexusLLM);
      mockInvoke.mockRejectedValueOnce(new Error('Initial model failed'));

      const context: RouterContext = {
        useCase: 'Code generation',
        contributor: { id: 'non-premium-user', secretBadge: false },
      };

      const result = await router.route('some code', context);

      expect(mockInvoke).toHaveBeenCalledTimes(1);
      expect(result.error).toBe('Initial model failed');
      expect(result.model).toBe('StarCoder2'); // The model we *intended* to use
      expect(result.fallbackModel).toBeUndefined();
    });
  });

  describe('Confidence Score Logic', () => {
    it('should return a high confidence score for a standard successful response', async () => {
      vi.mocked(invokeNexusLLM).mockResolvedValue({
        model: 'StarCoder2',
        response: 'This is a standard, long, and successful response from the model.',
      });
      const result = await router.route('some input', { useCase: 'Code generation' });
      expect((result.output as ReviewerOutput).confidence).toBe(0.95);
    });

    it('should return a reduced confidence score for a short response', async () => {
      vi.mocked(invokeNexusLLM).mockResolvedValue({
        model: 'StarCoder2',
        response: 'Short answer.',
      });
      const result = await router.route('some input', { useCase: 'Code generation' });
      console.log(result.output, result);
      expect((result.output as ReviewerOutput).confidence).toBe(0.85);
    });

    it('should return a reduced confidence score when a fallback occurs', async () => {
      const mockInvoke = vi.mocked(invokeNexusLLM);
      mockInvoke.mockRejectedValueOnce(new Error('Initial model failed')).mockResolvedValueOnce({
        model: 'Qwen2.5',
        response: 'This is a successful response from the fallback model.',
      });

      const context: RouterContext = {
        useCase: 'Code generation',
        contributor: { id: 'premium-fallback-user', secretBadge: true },
      };

      const result = await router.route('some code', context);
      expect((result.output as ReviewerOutput).confidence).toBe(0.75);
    });

    it('should return a very low confidence score when an error occurs', async () => {
      vi.mocked(invokeNexusLLM).mockRejectedValue(new Error('Model failed'));

      const context: RouterContext = {
        useCase: 'Code generation',
        contributor: { id: 'non-premium-user', secretBadge: false },
      };

      const result = await router.route('some code', context);
      expect((result.output as ReviewerOutput).confidence).toBe(0.1);
    });
  });
});
