import { ModelMetadata } from '../../types/models/models';

export const AUDIO_MODEL_REGISTRY: ModelMetadata[] = [
  // --- Speech-to-Text (STT) ---
  {
    name: 'Whisper Tiny',
    family: 'Whisper',
    developer: 'OpenAI',
    params: ['75M'],
    contextWindow: ['n/a'],
    useCases: [
      'Speech-to-text (STT)',
      'Real-time transcription',
      'Audio understanding',
      'Video captioning',
    ],
    license: 'MIT',
    requiresToken: false,
    role: 'listener',
  },
  {
    name: 'Whisper Base',
    family: 'Whisper',
    developer: 'OpenAI',
    params: ['150M'],
    contextWindow: ['n/a'],
    useCases: [
      'Speech-to-text (STT)',
      'Real-time transcription',
      'Audio understanding',
      'Video captioning',
    ],
    license: 'MIT',
    requiresToken: false,
    role: 'listener',
  },
  {
    name: 'Whisper Small',
    family: 'Whisper',
    developer: 'OpenAI',
    params: ['244M'],
    contextWindow: ['n/a'],
    useCases: ['Speech-to-text (STT)', 'Audio understanding', 'Video captioning'],
    license: 'MIT',
    requiresToken: false,
    role: 'listener',
  },
  {
    name: 'Whisper Large-V3',
    family: 'Whisper',
    developer: 'OpenAI',
    params: ['1.5B'],
    contextWindow: ['n/a'],
    useCases: ['Speech-to-text (STT)', 'Audio understanding', 'Video captioning'],
    license: 'MIT',
    requiresToken: false,
    role: 'listener',
  },
  {
    name: 'Vosk',
    family: 'Vosk',
    developer: 'Alpha Cephei',
    params: ['~50M–200M'],
    contextWindow: ['n/a'],
    useCases: [
      'Speech recognition',
      'Speech-to-text (STT)',
      'Real-time transcription',
      'Low-latency generation',
    ],
    license: 'Apache-2.0',
    requiresToken: false,
    role: 'listener',
  },
  {
    name: 'Coqui STT',
    family: 'Coqui',
    developer: 'Coqui AI',
    params: ['~200M–400M'],
    contextWindow: ['n/a'],
    useCases: [
      'Speech recognition',
      'Speech-to-text (STT)',
      'Real-time transcription',
      'Audio understanding',
    ],
    license: 'Coqui License',
    requiresToken: false,
    role: 'listener',
  },

  // --- Text-to-Speech (TTS) ---
  {
    name: 'XTTS v2',
    family: 'Coqui',
    developer: 'Coqui AI',
    params: ['400M'],
    contextWindow: ['n/a'],
    useCases: ['Text-to-speech (TTS)', 'Voice synthesis'],
    license: 'Coqui License',
    requiresToken: false,
    role: 'speaker',
  },
  {
    name: 'Bark',
    family: 'Suno',
    developer: 'Suno AI',
    params: ['400M'],
    contextWindow: ['n/a'],
    useCases: ['Text-to-speech (TTS)', 'Voice synthesis'],
    license: 'MIT',
    requiresToken: false,
    role: 'speaker',
  },
  {
    name: 'StyleTTS2',
    family: 'DiffTTS',
    developer: 'Academia Sinica',
    params: ['1B+'],
    contextWindow: ['n/a'],
    useCases: ['Text-to-speech (TTS)', 'Voice synthesis'],
    license: 'Research License',
    requiresToken: false,
    role: 'speaker',
  },
];
