import { ModelMetadata } from '../../types/models/models';

export const VISION_MODEL_REGISTRY: ModelMetadata[] = [
  {
    name: 'Qwen2.5',
    family: 'Qwen',
    developer: 'Alibaba Cloud',
    params: ['7B'],
    contextWindow: ['32k'],
    useCases: [
      'Image understanding',
      'Visual reasoning',
      'Image captioning',
      'Image recognition',
      'Object detection',
      'OCR (text from images)',
      'Question answering',
      'Knowledge retrieval',
      'Multilingual tasks',
    ],
    license: 'Apache-2.0',
    requiresToken: false,
    role: 'visualist',
  },
  {
    name: 'BLIP-2',
    family: 'BLIP',
    developer: 'Salesforce Research',
    params: ['FlanT5-XL'],
    contextWindow: ['n/a'],
    useCases: [
      'Image captioning',
      'Image understanding',
      'Visual reasoning',
      'Question answering',
      'Knowledge retrieval',
      'Image recognition',
    ],
    license: 'MIT',
    requiresToken: false,
    role: 'captioner',
  },
  {
    name: 'CLIP Interrogator',
    family: 'CLIP',
    developer: 'OpenAI / Community',
    params: ['ViT-L/14'],
    contextWindow: ['n/a'],
    useCases: [
      'Image understanding',
      'Image recognition',
      'Object detection',
      'Image captioning',
      'Visual reasoning',
      'Knowledge retrieval',
    ],
    license: 'MIT',
    requiresToken: false,
    role: 'visualist',
  },
];
