import { ModelMetadata } from '../types/models';

export const GEMINI_FLASH_2_5: ModelMetadata = {
  name: 'Gemini Flash 2.5',
  family: 'Gemini',
  developer: 'Google',
  params: ['2.5'],
  contextWindow: ['128k'],
  useCases: [
    'General text generation',
    'Long-form content generation',
    'Conversational AI',
    'Question answering',
    'Tool use',
    'Function calling',
    'RAG',
    'Summarization',
    'Efficient large-scale processing',
  ],
  license: 'Gemini License',
  requiresToken: true,
  role: 'prefect',
};

export const MODEL_REGISTRY: ModelMetadata[] = [
  {
    name: 'Llama-3.3',
    family: 'Llama',
    developer: 'Meta',
    params: ['70B'],
    contextWindow: ['128k'],
    useCases: [
      'General text generation',
      'Long-form content generation',
      'Code generation',
      'Code understanding',
      'Math reasoning',
      'Advanced reasoning',
      'Fine-tuning for specific domains',
    ],
    license: 'Llama Community License',
    requiresToken: false,
    role: 'generalist',
  },
  GEMINI_FLASH_2_5,
  {
    name: 'Gemma-3-27B-IT',
    family: 'Gemma',
    developer: 'Google',
    params: ['27B'],
    contextWindow: ['32k'],
    useCases: [
      'Summarization',
      'Question answering',
      'General text generation',
      'Multilingual tasks',
      'Long-form content generation',
      'Advanced reasoning',
      'Fine-tuning for specific domains',
    ],
    license: 'Gemma License',
    requiresToken: true,
    role: 'summarizer',
  },
  {
    name: 'Command R+',
    family: 'Command R',
    developer: 'Cohere',
    params: ['104B'],
    contextWindow: ['128k'],
    useCases: [
      'Conversational AI',
      'RAG',
      'Tool use',
      'Function calling',
      'Multilingual tasks',
      'Long-form content generation',
      'General text generation',
      'Code understanding',
    ],
    license: 'CC-BY-NC 4.0',
    requiresToken: false,
    role: 'router',
  },
  {
    name: 'Phi-4',
    family: 'Phi',
    developer: 'Microsoft',
    params: ['7B', '14B'],
    contextWindow: ['16k', '128k'],
    useCases: [
      'General text generation',
      'Multilingual tasks',
      'Code understanding',
      'Math reasoning',
      'Image understanding',
      'On-device inference',
    ],
    license: 'Microsoft Research License',
    requiresToken: false,
    role: 'generalist',
  },
  {
    name: 'Mistral',
    family: 'Mistral',
    developer: 'Mistral AI',
    params: ['7B'],
    contextWindow: ['32k'],
    useCases: [
      'General text generation',
      'Code generation',
      'Multilingual tasks',
      'Function calling',
      'Efficient large-scale processing',
    ],
    license: 'Apache 2.0',
    requiresToken: false,
    role: 'generalist',
  },
  {
    name: 'DeepSeek V3',
    family: 'DeepSeek',
    developer: 'DeepSeek AI',
    params: ['7B'],
    contextWindow: ['32k'],
    useCases: [
      'Code generation',
      'Code understanding',
      'Multilingual tasks',
      'Advanced reasoning',
      'General text generation',
    ],
    license: 'DeepSeek License',
    requiresToken: false,
    role: 'coder',
  },
];

export const MODEL_REGISTRY_BY_NAME: Record<string, ModelMetadata> = Object.fromEntries(
  MODEL_REGISTRY.map(model => [model.name, model])
);
