import { Plugin } from '../core/PluginManager';
import { LLMResponse, ReviewerOutput } from '../types/router';

export const ExplainerPlugin: Plugin = {
  name: 'explainer',
  // This plugin only acts on the output, so it doesn't need a `run` method.
  postRun: async (response: LLMResponse) => {
    const explanation = `[🤖 Explainer Note]: This response was generated by the ${response.model} model. The ExplainerPlugin was automatically activated to provide additional context for beginner contributors.`;

    if (typeof response.output === 'object') {
      (response.output as ReviewerOutput).explainer = explanation;
    } else {
      // This case should not happen with the new router logic, but it's a safe fallback.
      response.output = `${response.output}\n\n---\n${explanation}`;
    }

    return response;
  },
};
