import { Plugin } from '../core/PluginManager';
import { LLMResponse } from '../types/router';

export const ExplainerPlugin: Plugin = {
  name: 'explainer',
  // This plugin only acts on the output, so it doesn't need a `run` method.
  postRun: async (response: LLMResponse) => {
    const explanation = `\n\n---\n[🤖 Explainer Note]: This response was generated by the ${response.model} model. The ExplainerPlugin was automatically activated to provide additional context for beginner contributors.`;
    return {
      ...response,
      output: response.output + explanation,
    };
  },
};
