// src/plugins/FormatterPlugin.ts
import { Plugin } from '../core/PluginManager';
import { LLMResponse, ReviewerOutput } from '../types/router';

export const FormatterPlugin: Plugin = {
  name: 'formatter' as any,
  postRun: async (response: LLMResponse): Promise<LLMResponse> => {
    let confidence = 0.95; // Default confidence for successful responses

    // Adjust confidence based on response conditions
    if (response.fallbackModel) {
      confidence = 0.75;
    } else if (typeof response.output === 'string' && response.output.trim().length < 20) {
      confidence = 0.85;
    } else if (
      typeof response.output === 'object' &&
      'suggestion' in response.output &&
      response.output.suggestion.trim().length < 20
    ) {
      confidence = 0.85;
    }
    if (
      typeof response.output !== 'string' &&
      'suggestion' in response.output &&
      response.output.confidence
    )
      console.log(response.output.suggestion, response.output.confidence);
    if (response.error) {
      confidence = 0.1;
    }

    // Ensure output is always structured as ReviewerOutput with confidence
    const structuredOutput: ReviewerOutput = {
      suggestion:
        typeof response.output === 'string' ? response.output : response.output.suggestion,
      confidence, // Always include confidence
      reviewerNote: response.fallbackModel
        ? `Primary model failed. This response was generated by the fallback model: ${response.fallbackModel}.`
        : undefined,
    };

    return {
      ...response,
      output: structuredOutput,
    };
  },
};
